<?php
use App\Filters\AuthFilter;
use FastRoute\RouteCollector;
use App\Controllers\Auth\LoginController;
use App\Controllers\Auth\LogoutController;
use App\Controllers\PageControllers\HomeController;
use App\Controllers\PageControllers\DashboardController;
use App\Controllers\EntityControllers\MaterielController;
use App\Controllers\EntityControllers\CategorieController;
use App\Controllers\PageControllers\MaterielPageController;
use App\Controllers\EntityControllers\ReservationController;
use App\Controllers\EntityControllers\UtilisateurController;
use App\Controllers\EntityControllers\TypeMaterielController;
use App\Controllers\PageControllers\GestionMaterielController;
use App\Controllers\PageControllers\GestionReservationController;
use App\Controllers\PageControllers\GestionUtilisateurController;
use App\Controllers\PageControllers\CreationReservationController;
use App\Controllers\PageControllers\CreationUtilisateurController;
use App\Controllers\PageControllers\ModifierReservationController;

return function (RouteCollector $route) {
    $route->get('/', [HomeController::class, 'index']);
    $route->post('/connexion', [LoginController::class, 'login']);
    $route->get('/deconnexion', [LogoutController::class, 'logout']);
    $route->get('/dashboard', [DashboardController::class, 'index']);
    $route->post('/API/dashboard/get-reservations', [ReservationController::class, 'getAllReservationFromIdTypeMaterial']);
    $route->get('/gestion-materiel', [GestionMaterielController::class, 'index']);
    $route->post('/gestion-materiel/create-categorie', [CategorieController::class, 'create']);
    $route->post('/gestion-materiel/create-type-materiel', [TypeMaterielController::class, 'create']);
    $route->post('/gestion-materiel/get-cards', [GestionMaterielController::class, 'getCards']);
    $route->post('/gestion-materiel/save-card', [MaterielController::class, 'create']);
    $route->post('/gestion-materiel/get-material-list', [MaterielController::class, 'getMaterielsByTypeId']);
    $route->get('/gestion-materiel/materiel/{id:\d+}', [MaterielPageController::class, 'index']);
    $route->post('/gestion-materiel/materiel/modifier', [MaterielController::class, 'modify']);
    $route->get('/gestion-materiel/materiel/supprimer/{id:\d+}', [MaterielController::class, 'delete']);
    $route->get('/gestion-utilisateur', [GestionUtilisateurController::class, 'index']);
    $route->get('/gestion-utilisateur/nouvel-utilisateur', [CreationUtilisateurController::class, 'index']);
    $route->post('/gestion-utilisateur/creation-utilisateur', [UtilisateurController::class, 'create']);
    $route->get('/gestion-utilisateur/modifier/{id:\d+}', [UtilisateurController::class, 'modify']);
    $route->get('/gestion-utilisateur/supprimer/{id:\d+}', [UtilisateurController::class, 'delete']);
    $route->get('/reserver-materiel', [CreationReservationController::class, 'index']);
    $route->post('/create-reservation', [ReservationController::class, 'create']);
    $route->post('/modify-reservation', [ReservationController::class, 'modify']);
    $route->post('/API/verify-disponibility-material', [MaterielController::class, 'checkDisponibility']);
    $route->get('/gestion-reservation', [GestionReservationController::class, 'index']);
    $route->get('/gestion-reservation/modifier/{id:\d+}', [ModifierReservationController::class, 'index']);
    $route->get('/gestion-reservation/delete/{id:\d+}', [ReservationController::class, 'delete']);
    //$route->addRoute('GET', '/user/{id:\d+}', ['App\Controller\UserController', 'show']);
    //$route->addRoute('POST', '/user/create', ['App\Controller\UserController', 'create']);
};
